name: Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  install-terraform:
    runs-on: [self-hosted, git-workflow]
    steps:
      - name: Check if Terraform is already installed
        id: check-terraform
        run: |
          if command -v terraform &> /dev/null; then
            echo "Terraform is already installed."
            echo "terraform_installed=true" >> $GITHUB_ENV
          else
            echo "terraform_installed=false" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Prevent Re-run if Terraform is Installed
        if: env.terraform_installed == 'true'
        run: exit 0

      - name: Install Terraform
        if: env.terraform_installed == 'false'
        run: |
          sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
          wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
          gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get install terraform -y
          echo "terraform_installed=true" >> $GITHUB_ENV
          echo "Terraform installed successfully!"

      - name: Verify Terraform Installation
        if: env.terraform_installed == 'true'
        run: terraform --version

  install-aws-cli:
    runs-on: [self-hosted, git-workflow]
    steps:
      - name: Check if AWS-CLI is already installed
        id: check-aws-cli
        run: |
          if command -v aws &> /dev/null; then
            echo "AWS CLI is already installed."
            echo "aws_installed=true" >> $GITHUB_ENV
          else
            echo "aws_installed=false" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Prevent Re-run if AWS CLI is Installed
        if: env.aws_installed == 'true'
        run: exit 0

      - name: Install AWS CLI
        if: env.aws_installed == 'false'
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          sudo apt-get install unzip -y
          sudo unzip awscliv2.zip
          sudo ./aws/install
          sudo rm -rf aws
          echo "aws_installed=true" >> $GITHUB_ENV
          echo "AWS CLI installed successfully!"

      - name: Verify AWS CLI Installation
        if: env.aws_installed == 'true'
        run: aws --version
